# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Bookworm
tagline:             'textual experimentation'
description:         'An exploration of text analytics and fiction.'
url:                 http://bookworm.davidlday.com
baseurl:             /
paginate:            5
disqus_shortname:    bookworm-analytics

# About/contact
author:
  name:              David L. Day
  url:               https://twitter.com/dday376
  email:             david@davidlday.com

# Custom vars
version:             0.0.1
